language: php 

env:
  global:
    - "ARTIFACTS_AWS_REGION=us-east-1"
    - "ARTIFACTS_S3_BUCKET=silverstripe-travis-artifacts"
    - "ARTIFACTS_BASE_URL=https://s3.amazonaws.com/silverstripe-travis-artifacts/artifacts"
    - secure: "nPghMoAxhJoZIcSbnFHbHY1m/qolXlZ9Mo+QX1EJ4IiZDxJGRqcV8LiBpW7uVBd68x9mufFDWqxUKrKw5m0nxjTlJB7upyavaq2hq0jYBueLJWA0kHOS6V5hn4xbJN3s1Z/tdCvvGsEH1znfSWVQUkwQgUBxMBT9+UH1ihxt2tc="
    - secure: "H4UGFJ5XB38c9oyw3uMrDUKnRmz9/Qk8MCo9WZT+/jxB8OU9PykzLgL51XCJ+iOoKcpov/z1vH2MQdwGrIivxCtv+XvWv57nVK6KU9F4F93VGZgTOBuUWwf4njs4Ak8CSTx3IBj+S1PgzK++0LrPiJZvkMIG2qaxlQTH14ggjKI="

matrix:
  include:
    - php: 5.4
      env: DB=MYSQL CORE_RELEASE=3.1 BEHAT_TEST=1

before_script:
 - "if [ \"$BEHAT_TEST\" = \"1\" ]; then gem install travis-artifacts; fi"
 - composer self-update
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - "if [ \"$BEHAT_TEST\" = \"\" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss; fi"
 - "if [ \"$BEHAT_TEST\" = \"1\" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require silverstripe/behat-extension; fi"
 - cd ~/builds/ss
 - php ~/travis-support/travis_setup_selenium.php --if-env BEHAT_TEST
 - php ~/travis-support/travis_setup_php54_webserver.php --if-env BEHAT_TEST

script: 
 - "if [ \"$BEHAT_TEST\" = \"\" ]; then phpunit framework/tests; fi"
 - "if [ \"$BEHAT_TEST\" = \"1\" ]; then vendor/bin/behat --name 'list all users' @framework/manage-users.feature; fi"

after_script:
 - php ~/travis-support/travis_upload_artifacts.php --if-env 'BEHAT_TEST,ARTIFACTS_AWS_ACCESS_KEY_ID' --artifacts-path ~/builds/ss/artifacts --target-path artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID

branches:
  except:
    - 2.1
    - 2.2
    - 2.3
    - translation-staging

notifications:
  irc:
    channels:
     - "irc.freenode.org#silverstripe"

#  global:
#   - secure: "AZmjVPtUD8JBA7ag4ULlEwEKXSEZbIUjDHeRBFugaOtdsn5yigGLmwYbzsg2tq7k7UkdbbAlGct0SUbiRJb9F2wPA5+eUd/p49fgDIU6CTSWIlT87H2BwgOrxKwS9sDwxLptPFM6vWQ8JKYSNGmVIepie9kQZbu4L2k5k6B69jQ="
#   - secure: "f3kKpUn9cS5K+p/E52cMqN18cDApol/43LanDmHO6mo3iRAztk3jZLyfNOUq6JASKMqdh8+9kencRpEoaAYbcQnDPoZsT9POResiJ9/ADKB6RwWy+lcFHUp9E2Zf/x2VRh9FmXEguDhpWzkJqzWYJGCSig1IBp/+TjzKnsjQHIY="
#
# - php ~/travis-support/travis_setup_sauceconnect.php --if-env BEHAT_TEST --username ${SAUCE_USERNAME} --access-key ${SAUCE_ACCESS_KEY} --tunnel-identifier ${TRAVIS_JOB_NUMBER} --base-url http://localhost
